// This file is autogenerated from the 'ContentSourceGenerator'
// DO NOT EDIT!
public static class ContentDirectory 
{
  public static string _mgstats => ".mgstats";
  public static string test_map_tmx => "test-map.tmx";
  public static string tileset_png => "tileset.png";
 public static class Fonts 
 {
   public static string Consolas_ttf => "Fonts/Consolas.ttf";
   public static string font_spritefont => "Fonts/font.spritefont";
   public static string RandomWednesday_ttf => "Fonts/Random Wednesday.ttf";
   public static string Roboto_Regular_ttf => "Fonts/Roboto-Regular.ttf";
  public static class MoreFonts 
  {
    public static string Freedom_10eM_ttf => "Fonts/MoreFonts/Freedom-10eM.ttf";
  }
 }
   public static class Shaders 
   {
     public static string _mgstats => "Shaders/.mgstats";
     public static string effect_fx => "Shaders/effect.fx";
     public static string effect2_fx => "Shaders/effect2.fx";
     public static string FieldFontEffect_fx => "Shaders/FieldFontEffect.fx";
    public static class MoreShaders 
    {
      public static string effect_fx => "Shaders/MoreShaders/effect.fx";
    }
   }
     public static class Textures 
     {
      public static class frogpack_spritesheets 
      {
        public static string fly_fly_strip2_png => "Textures/frogpack_spritesheets/fly_fly_strip2.png";
        public static string frog_attackdiagonal_strip6_png => "Textures/frogpack_spritesheets/frog_attackdiagonal_strip6.png";
        public static string frog_attackforward_strip6_png => "Textures/frogpack_spritesheets/frog_attackforward_strip6.png";
        public static string frog_attackup_strip6_png => "Textures/frogpack_spritesheets/frog_attackup_strip6.png";
        public static string frog_croak_strip7_png => "Textures/frogpack_spritesheets/frog_croak_strip7.png";
        public static string frog_dash_strip8_png => "Textures/frogpack_spritesheets/frog_dash_strip8.png";
        public static string frog_die_strip12_png => "Textures/frogpack_spritesheets/frog_die_strip12.png";
        public static string frog_fall_strip1_png => "Textures/frogpack_spritesheets/frog_fall_strip1.png";
        public static string frog_fright_strip8_png => "Textures/frogpack_spritesheets/frog_fright_strip8.png";
        public static string frog_hop_strip6_png => "Textures/frogpack_spritesheets/frog_hop_strip6.png";
        public static string frog_hurt_strip5_png => "Textures/frogpack_spritesheets/frog_hurt_strip5.png";
        public static string frog_idle_strip4_png => "Textures/frogpack_spritesheets/frog_idle_strip4.png";
        public static string frog_jump_strip12_png => "Textures/frogpack_spritesheets/frog_jump_strip12.png";
        public static string frog_land_strip3_png => "Textures/frogpack_spritesheets/frog_land_strip3.png";
        public static string frog_swimattackdiagonal_strip6_png => "Textures/frogpack_spritesheets/frog_swimattackdiagonal_strip6.png";
        public static string frog_swimattackforward_strip6_png => "Textures/frogpack_spritesheets/frog_swimattackforward_strip6.png";
        public static string frog_swimattackup_strip6_png => "Textures/frogpack_spritesheets/frog_swimattackup_strip6.png";
        public static string frog_swimforward_strip6_png => "Textures/frogpack_spritesheets/frog_swimforward_strip6.png";
        public static string frog_swimidle_strip4_png => "Textures/frogpack_spritesheets/frog_swimidle_strip4.png";
        public static string full_sheet_export_png => "Textures/frogpack_spritesheets/full_sheet-export.png";
        public static string full_sheet_Sheet_png => "Textures/frogpack_spritesheets/full_sheet-Sheet.png";
        public static string full_sheet_png => "Textures/frogpack_spritesheets/full_sheet.png";
      }
       public static class MainMenu 
       {
         public static string _mgstats => "Textures/MainMenu/.mgstats";
         public static string background_mainmenu_png => "Textures/MainMenu/background_mainmenu.png";
       }
        public static class Physics 
        {
          public static string blank_png => "Textures/Physics/blank.png";
          public static string blank3_png => "Textures/Physics/blank3.png";
          public static string dots_png => "Textures/Physics/dots.png";
          public static string pavement_png => "Textures/Physics/pavement.png";
          public static string squares_png => "Textures/Physics/squares.png";
          public static string waves_png => "Textures/Physics/waves.png";
        }
         public static class Game 
         {
          public static class Frog 
          {
            public static string frog_animations_aseprite => "Textures/Game/Frog/frog_animations.aseprite";
            public static class frog_animations_Tags //Animation Tags for frog_animations_aseprite
            {
              public static string Lick => "lick";
              public static string Hop => "hop";
              public static string Idle => "idle";
              public static string Fall => "fall";
              public static string Dash => "dash";
              public static string Lick_Diagonal => "lick_diagonal";
              public static string Lick_Up => "lick_up";
              public static string Hurt => "hurt";
              public static string Die => "die";
              public static string Jump => "jump";
            }
            public static string frog_animations_combined_json => "Textures/Game/Frog/frog_animations_combined.json";
            public static string frog_animations_combined_png => "Textures/Game/Frog/frog_animations_combined.png";
          }
         }
     }
}
