// This file is autogenerated from the 'ContentSourceGenerator'
// DO NOT EDIT!
public static class ContentDirectory 
{
  public static string _mgstats => ".mgstats";
  public static string Content_mgcb => "Content.mgcb";
  public static string Contentless_json => "Contentless.json";
 public static class Fonts 
 {
   public static string Consolas_ttf => "Fonts/Consolas.ttf";
   public static string RandomWednesday_ttf => "Fonts/Random Wednesday.ttf";
   public static string Roboto_Regular_ttf => "Fonts/Roboto-Regular.ttf";
   public static string font_spritefont => "Fonts/font.spritefont";
  public static class MoreFonts 
  {
    public static string Freedom_10eM_ttf => "Fonts/MoreFonts/Freedom-10eM.ttf";
  }
 }
   public static class Shaders 
   {
     public static string _mgstats => "Shaders/.mgstats";
     public static string FieldFontEffect_fx => "Shaders/FieldFontEffect.fx";
     public static string effect_fx => "Shaders/effect.fx";
     public static string effect2_fx => "Shaders/effect2.fx";
    public static class MoreShaders 
    {
      public static string effect_fx => "Shaders/MoreShaders/effect.fx";
    }
   }
     public static class Textures 
     {
      public static class MainMenu 
      {
        public static string _mgstats => "Textures/MainMenu/.mgstats";
        public static string background_mainmenu_png => "Textures/MainMenu/background_mainmenu.png";
      }
     }
}
